### ISSUE TITLE
paho.mqtt.client - API change

### ISSUE THREAD

**Issue by RadioNur** [pdxlocations/Meshtastic-MQTT-Connect#22]
Recieved the following error after pip installing required libraries:

Exception ignored in: <function Client.__del__ at 0x0000016A8F4ADEE0>
Traceback (most recent call last):
  File "C:\Users\mking\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\paho\mqtt\client.py", line 874, in __del__
    self._reset_sockets()
  File "C:\Users\mking\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\paho\mqtt\client.py", line 1133, in _reset_sockets
    self._sock_close()
  File "C:\Users\mking\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\paho\mqtt\client.py", line 1119, in _sock_close
    if not self._sock:
           ^^^^^^^^^^
AttributeError: 'Client' object has no attribute '_sock'
Traceback (most recent call last):
  File "F:\Hobbies\Lora\Meshtastic\meshtastic-mqtt-connect.py", line 1215, in <module>
    client = mqtt.Client(client_id="", clean_session=True, userdata=None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Client.__init__() missing 1 required positional argument: 'callback_api_version'

Did some digging on the Client object at paho, looks like API has had a minor change.

Line 1215: client = mqtt.Client(client_id="", clean_session=True, userdata=None), tested both versions, seems that you want version 1 for compatibility, the following fixes it, it boots ok and was able to interact with the client, send recieve messages etc.  As this is such a minor change I opted not to create a fork

Fix: client = mqtt.Client(**mqtt.CallbackAPIVersion.VERSION1**, client_id="", clean_session=True, userdata=None)

**Comment by pdxlocations** [comment]
Thank you!  I added the callback for new paho 2.0 compatibility.
