### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by BjornB2** [pdxlocations/Meshtastic-MQTT-Connect#26]
Hey, 

I installed the requirements, but I get this error:

```
bjorn@MacBook-Air-van-Bjorn Meshtastic-MQTT-Connect-main % python3 meshtastic-mqtt-connect.py
Traceback (most recent call last):
  File "/Users/bjorn/Downloads/Meshtastic-MQTT-Connect-main/meshtastic-mqtt-connect.py", line 11, in <module>
    import tkinter as tk
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

tk is installed

```
bjorn@MacBook-Air-van-Bjorn Meshtastic-MQTT-Connect-main % pip3 install tk
DEPRECATION: Loading egg at /opt/homebrew/lib/python3.11/site-packages/oauthlib-3.2.2-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /opt/homebrew/lib/python3.11/site-packages/rmapy-0.3.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /opt/homebrew/lib/python3.11/site-packages/requests-2.28.2-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /opt/homebrew/lib/python3.11/site-packages/websocket_client-1.5.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /opt/homebrew/lib/python3.11/site-packages/urllib3-1.26.15-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /opt/homebrew/lib/python3.11/site-packages/charset_normalizer-3.1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /opt/homebrew/lib/python3.11/site-packages/requests_oauthlib-1.3.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /opt/homebrew/lib/python3.11/site-packages/certifi-2022.12.7-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /opt/homebrew/lib/python3.11/site-packages/idna-3.4-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /opt/homebrew/lib/python3.11/site-packages/pyaml-19.4.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /opt/homebrew/lib/python3.11/site-packages/PyYAML-6.0.1-py3.11-macosx-13-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /opt/homebrew/lib/python3.11/site-packages/TeslaPy-2.7.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: tk in /opt/homebrew/lib/python3.11/site-packages (0.1.0)
bjorn@MacBook-Air-van-Bjorn Meshtastic-MQTT-Connect-main % 
```

Am I missing something?

**Comment by pdxlocations** [comment]
I'm no eggspert but I'd try reinstalling Python.

**Comment by pdxlocations** [comment]
Or try the fix here:
https://stackoverflow.com/questions/68554782/modulenotfounderror-no-module-named-tkinter-on-macos
`brew install python-tk`

**Comment by BjornB2** [comment]
I'll try tomorrow thanks

**Comment by pdxlocations** [comment]
Did you resolve this?

**Comment by BjornB2** [comment]
To be honest, I forgot to try. Will try and let you know.

**Comment by BjornB2** [comment]
Ok I now get past that error but the next one arises I'm afraid.

```
Traceback (most recent call last):
  File "/Users/bjornheirman/Downloads/Meshtastic-MQTT-Connect/meshtastic-mqtt-connect.py", line 13, in <module>
    import paho.mqtt.client as mqtt
ModuleNotFoundError: No module named 'paho'
```

I did run 

`brew install libpaho-mqtt`

**Comment by pdxlocations** [comment]
Google is telling me that command will install paho for C, not Python.  Any reason you aren't using pip as advised in the readme?

**Comment by BjornB2** [comment]
Also tried that but didn't work so I tried the brew install and that worked. As with tkinter it worked better with brew I thought that would be a good idea. 
Thanks for your help, but please don't put any more effort in my case. I might try again in the future but not really time for it now anyway.

```
pip3 install paho-mqtt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-brew-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-brew packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

**Comment by pdxlocations** [comment]
Since this seems to be an issue with your Python install and not with the script I'm going to close this.
