### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by william-stearns** [pdxlocations/Meshtastic-MQTT-Connect#49]
Meshtastic-MQTT-Connect Version 0.8.2 running under python 3.11 on MacOS with the following changes in the code:
-print_text_message = False
+print_text_message = True
@@ -40 +40 @@
-print_position_report = False
+print_position_report = True
@@ -45 +45 @@
-display_private_dms = False
+display_private_dms = True
@@ -47 +47 @@
-record_locations = False
+record_locations = True

    Left it running for the evening and when I came back I had this on the console:
...
From: TTBE, lat: 32.6216903, lon: -117.00677, alt: 135, PDOP: 0, speed: 0, track: 0, sats: 12, RSSI: -122
Exception in thread Thread-1 (mqtt_thread):
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wstearns/med/from_others/Meshtastic-MQTT-Connect-main.20240710/meshtastic-mqtt-connect.py", line 1464, in mqtt_thread
    client.loop()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paho/mqtt/client.py", line 1635, in loop
    return self._loop(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paho/mqtt/client.py", line 1686, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paho/mqtt/client.py", line 2100, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paho/mqtt/client.py", line 3142, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paho/mqtt/client.py", line 3808, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paho/mqtt/client.py", line 4145, in _handle_publish
    self._handle_on_message(message)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paho/mqtt/client.py", line 4501, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/Users/wstearns/med/from_others/Meshtastic-MQTT-Connect-main.20240710/meshtastic-mqtt-connect.py", line 355, in on_message
    env.ParseFromString(mp.decoded.payload)
google.protobuf.message.DecodeError: Error parsing message

**Comment by william-stearns** [comment]
With apologies because this isn't fixing the problem. perhaps something like:
```    elif mp.decoded.portnum == portnums_pb2.POSITION_APP:
        pos = mesh_pb2.Position()
        try:
            pos.ParseFromString(mp.decoded.payload)
            if record_locations:
                maybe_store_position_in_db(getattr(mp, "from"), pos, getattr(mp, "rx_rssi"))
        except google.protobuf.message.DecodeError:
            if debug:
                print("POSITION_APP message parsing error")```

**Comment by pdxlocations** [comment]
I added some error handling (I think) and updated the protobuf imports for meshtastic cli 2.3.13+.
Give this a shot and let me know if it helps.  Thanks for testing the script!

**Comment by william-stearns** [comment]
The new version seems to be running stably for most of the day.  Thanks for
making the changes!

**Comment by pdxlocations** [comment]
Great!  Thanks for the report.
